[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.qa]
script = [
    "echo \"Running cargo check\"",
    "cargo check -q --all-features",
    "echo \"Running cargo fmt\"",
    "cargo fmt -- --check",
    "echo \"Running cargo clippy\"",
    "cargo clippy -- -D warnings",
    "echo \"Running cargo test\"",
    "cargo test",
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

